{% set name = "file-tree" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d36dd6e0a4f2074014180f4a60ff091e10eebe0255f0bc2b855a039ebfec71df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - hatchling
  run:
    - numpy
    - pandas
    - parse
    - python >=3.10
    - xarray
    - rich

test:
  imports:
    - file_tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/file-tree
  summary: Describe structure directory for pipeline
  license: MIT
  license_file: LICENSE
  doc_url: https://open.win.ox.ac.uk/pages/ndcn0236/file-tree

extra:
  recipe-maintainers:
    - MichielCottaar
