{% set python_min = "3.10" %}
{% set name = "file-tree" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f46705e9e51f2ac2648ac4ff849207e4574d2ac53e648286242df24c45598db9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv-build
  run:
    - numpy
    - pandas
    - parse
    - python >={{ python_min }}
    - xarray
    - rich

test:
  imports:
    - file_tree
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.fmrib.ox.ac.uk/fsl/file-tree
  summary: Describe structure directory for pipeline
  license: MIT
  license_file: LICENSE
  doc_url: https://open.oxcin.ox.ac.uk/pages/fsl/file-tree/stable

extra:
  recipe-maintainers:
    - MichielCottaar
