{% set name = "file-tree" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/file-tree-{{ version }}.tar.gz
  sha256: 41568ce6ab5f5739cb406440175fe4ea6b2babb9d7dd6af934a98b5d226bcf35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - parse
    - python >=3.6
    - xarray
    - rich
    - textual

test:
  imports:
    - file_tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/file-tree
  summary: Describe structure directory for pipeline
  license: MIT
  license_file: LICENSE
  doc_url: https://open.win.ox.ac.uk/pages/ndcn0236/file-tree

extra:
  recipe-maintainers:
    - MichielCottaar
