{% set name = "file-tree" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/file-tree-{{ version }}.tar.gz
  sha256: 0486186f6585a3716f4032bc83bf9ba280ab4c74acfe3890bd35ecf1d64bd982

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - parse
    - python >=3.6
    - xarray

test:
  imports:
    - file_tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/file-tree
  summary: Describe structure directory for pipeline
  license: MIT
  license_file: LICENSE
  doc_url: https://open.win.ox.ac.uk/pages/ndcn0236/file-tree

extra:
  recipe-maintainers:
    - MichielCottaar
